global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "backend"
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["backend:5001"]

  - job_name: "agent-service"
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["agent-service:5002"]
